### ISSUE TITLE
can't find the npm module

### ISSUE THREAD

**Issue by fisnik** [PinionTech/winston-s3#3]
Tried to use this module, but somehow the package manager can't get the object.

var winston_S3 = require('winston-s3').S3;  // is always undefined. 

I tried to compile the source into js, and replaced the contents of winston-s3.js with the js compiled source - things seem to be working that way, however, the logs are not being written ultimately to the bucket.

**Comment by skpulla** [comment]
I was getting the same error when I tried to use the example code. But using the following line fixed it.

var winstonS3 = require('winston-s3');

instead of

var winstonS3 = require('winston-s3').S3;

Is this the expected behaviour? If so, can you please update the example in the readme file?

**Comment by davidbanham** [comment]
Good catch! I guess that example was out of date and nobody noticed until now. Thanks for picking it up.

**Comment by skpulla** [comment]
@davidbanham Cheers
