### ISSUE TITLE
Do not work on Windows

### ISSUE THREAD

**Issue by jingzhaoou** [PinionTech/winston-s3#5]
Ran into 

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open 'C:\spring-workspace-440\temp\s3logs\s3logger_2015-07-18T05:17:46.555Z'
    at Error (native)
```

on my Windows 8 machine. This is because "s3logger_2015-07-18T05:17:46.555Z" is not a valid file name on Windows platform. Suggest to use other file names that work on Windows as well. 

Thanks,
Jingzhao

**Comment by davidbanham** [comment]
Thanks for the report! I'm not a Windows user, so could you please help me out by pointing out which aspect of the filename is causing the issue? I'm guessing it's the presence of the `:` but it might also be the `.`

**Comment by jingzhaoou** [comment]
I fixed the issue by changing the following line in ```winston_s3.coffee```.

```
  return fs.createWriteStream path.join logFilePath, 's3logger_' + (new Date().toISOString()).replace(/:/g, '_')
```

That is, I replace ```:``` with ```_```.

**Comment by davidbanham** [comment]
Thanks for the report and fix! I've incorporated that and pushed to npm as a new major version since the filenames could be considered an API.
